### ISSUE TITLE
Bots update problem

### ISSUE THREAD

**Issue by TigerNetv** [Raffy27/OrionPanel#2]
Great Project, but there is problem with bot update (server side)..
even if bot offline, it's show online..

**Comment by Raffy27** [comment]
The project is not meant to have realtime updates (being an HTTPS botnet, calculating online time is not very straightforward, all sorts of delays an inaccuracies exist), so the Server assumes that bots that have not responded for **3 minutes** are offline. Until that time is up, bots will be considered online, **even if you specifically kill them on the host**.

See the [isBotOnline](https://github.com/Raffy27/OrionServer/blob/e4d38d280da2070a41e09de139d90ab35574b3ed/database.js#L237) function of OrionServer for more details.

If you encounter bots that are shown as online even after the 3 minutes are up, please provide a description of the steps that you have taken along with your configuration and environment, so that I may reproduce the issue and find out what's causing it.
